In [1]:
import pandas as pd
import json

In [2]:
with open('C:\\Users\\JosephMoffatt\\OneDrive - Thought Logic\\Desktop\\GitHubRepos\\dataengineeringprojects\\DataEngineeringProjects\\auxdata\\YourLibrary.json','r', encoding='utf-8') as f:
    data = json.load(f)
MyLibrarydf = pd.DataFrame(data['tracks'])
MyLibrarydf.head()

,artist,album,track,uri
0,New Edition,New Edition,Mr. Telephone Man,spotify:track:4DiNls6kFmF1ZittKsPsTc
1,El Alfa,El Hombre,Suave (Remix),spotify:track:4phvdPGXE8MGXsTBhqB5ht
2,Luis Miguel Hernandez,Última Сampana,La Luna y Carmela,spotify:track:1Jfl8NMQKN9TbLTE8uJyPR
3,Marvin Gaye,United,Ain't No Mountain High Enough,spotify:track:7tqhbajSfrz2F7E1Z75ASX
4,Burna Boy,"Love, Damini",Last Last,spotify:track:57DarSfRMIVRCeDBGW0l5S

In [3]:
# From a JSON file
Marqueedf = pd.read_json('C:\\Users\\JosephMoffatt\\OneDrive - Thought Logic\\Desktop\\GitHubRepos\\dataengineeringprojects\\DataEngineeringProjects\\auxdata\\Marquee.json')
Marqueedf.head()

     artistName                      segment
0    Big Boogie  Previously Active Listeners
1          Iyaz  Previously Active Listeners
2     Ice Spice  Previously Active Listeners
3  Ben Carrillo  Previously Active Listeners
4      Pianaura  Previously Active Listeners

In [4]:
df_merged = pd.merge(MyLibrarydf, Marqueedf, left_on='artist', right_on='artistName', how='inner')
df_merged = df_merged.drop(columns=['artistName']).rename(columns={'segment': 'artist_segment'})
df_merged

,artist,album,track,uri,artist_segment
0,New Edition,New Edition,Mr. Telephone Man,spotify:track:4DiNls6kFmF1ZittKsPsTc,Light listeners
1,El Alfa,El Hombre,Suave (Remix),spotify:track:4phvdPGXE8MGXsTBhqB5ht,Moderate listeners
2,Luis Miguel Hernandez,Última Сampana,La Luna y Carmela,spotify:track:1Jfl8NMQKN9TbLTE8uJyPR,Light listeners
3,Marvin Gaye,United,Ain't No Mountain High Enough,spotify:track:7tqhbajSfrz2F7E1Z75ASX,Previously Active Listeners
4,Burna Boy,"Love, Damini",Last Last,spotify:track:57DarSfRMIVRCeDBGW0l5S,Moderate listeners
...,...,...,...,...,...
524,Kes,Cocoa Tea,Cocoa Tea,spotify:track:1x89dD1bENfCHL6MiZurDI,Previously Active Listeners
525,Mariah Carey,The Emancipation of Mimi,We Belong Together,spotify:track:3LmvfNUQtglbTrydsdIqFU,Previously Active Listeners
526,Cartoon,On & On,On & On,spotify:track:2uZWffKoemZDI0gHcBEcDc,Previously Active Listeners
527,Reik,Pero Te Conocí,Pero Te Conocí,spotify:track:3GoZFM9oqXO68BQXBA1Czv,Previously Active Listeners
528,BigXthaPlug,The Largest,The Largest,spotify:track:1F5Qp0SJS0QUfqIoQggrLz,Light listeners

In [5]:
with open('C:\\Users\\JosephMoffatt\\OneDrive - Thought Logic\\Desktop\\GitHubRepos\\dataengineeringprojects\\DataEngineeringProjects\\auxdata\\TasteProfile.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Use json_normalize instead of pd.DataFrame()
df = pd.json_normalize(data['tasteProfile'])

df.head()

,musicalIdentity,podcastTaste,audiobookTaste,contentRhythms,artistUris,showUris,audiobookUris
0,Your musical identity is deeply rooted in **La...,Your podcast listening is focused on **Spanish...,Tell us about your taste or start listening to...,"Your days are heavily soundtracked by music, w...","[spotify:artist:7bXgB6jMjp9ATFy66eO08Z, spotif...","[spotify:show:0SdDSgKLwkobIO5Jj8iPmP, spotify:...",[]

In [6]:
with open('C:\\Users\\JosephMoffatt\\OneDrive - Thought Logic\\Desktop\\GitHubRepos\\dataengineeringprojects\\DataEngineeringProjects\\auxdata\\YourSoundCapsule.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

df = pd.json_normalize(data['stats'])

# Explode the list into individual rows
df_exploded_topTracks = df.explode('topTracks')

# Normalize the dicts into separate columns
normalized_topTracks = pd.json_normalize(df_exploded_topTracks['topTracks'])

normalized_topTracks.head()

,name,streamCount,secondsPlayed
0,Una Vez,12,1957
1,Crayola,9,1832
2,she goes by. - KayArchon Remix,9,1073
3,"Muzan vs Hashira ""Demon Slayer Hashira Trainin...",5,1532
4,Waves,5,1114

In [7]:
with open('C:\\Users\\JosephMoffatt\\OneDrive - Thought Logic\\Desktop\\GitHubRepos\\dataengineeringprojects\\DataEngineeringProjects\\auxdata\\SearchQueries.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Use json_normalize instead of pd.DataFrame()
df = pd.json_normalize(data)

df

,platform,searchTime,searchQuery,searchInteractionURIs
0,IPHONE,2026-02-10T01:30:28.160Z[UTC],sals,"[spotify:track:2i8otid5VKKnEaseBVO1vq, spotify..."
1,IPHONE,2026-02-10T11:08:56.866Z[UTC],wgin,[spotify:track:1TKNkFNRWL5YcefJeIkfKz]
2,IPHONE,2026-02-10T11:29:40.242Z[UTC],dar,[spotify:track:0BSGwoTRRZ0q58WB8RXLO3]
3,,2026-02-10T12:42:26.434Z[UTC],ka,[]
4,IPHONE,2026-02-10T12:42:27.151Z[UTC],kai th,"[spotify:search:kai+theme, spotify:track:5JD6g..."
...,...,...,...,...
1775,,2026-05-09T19:35:22.630Z[UTC],h,[]
1776,IPHONE,2026-05-09T19:35:23.211Z[UTC],he,[spotify:track:3VvA1wSxukMLsvXoXtlwWx]
1777,IPHONE,2026-05-09T19:39:06.722Z[UTC],kaf,[spotify:artist:5RLb16s3zfrdWdRF0l7xij]
1778,,2026-05-09T22:05:21.547Z[UTC],y,[]
1779,IPHONE,2026-05-09T22:05:22.288Z[UTC],you,[spotify:track:1Lhwn4PqeGpM4LTVUowW76]

In [8]:
with open('C:\\Users\\JosephMoffatt\\OneDrive - Thought Logic\\Desktop\\GitHubRepos\\dataengineeringprojects\\DataEngineeringProjects\\auxdata\\Playlist1.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

In [23]:

df = pd.json_normalize(data['playlists'])
exploded_df = df.explode('items')
exploded_df

,name,lastModifiedDate,collaborators,items,numberOfFollowers
0,Si necesitas ir allá…,2026-03-16,[],"{'track': {'trackName': 'DARK ARIA -ARISE-', '...",0
0,Si necesitas ir allá…,2026-03-16,[],{'track': {'trackName': 'To the Infinity Castl...,0
0,Si necesitas ir allá…,2026-03-16,[],"{'track': {'trackName': 'Muzan vs Hashira ""Dem...",0
0,Si necesitas ir allá…,2026-03-16,[],{'track': {'trackName': 'Akaza Entrance Theme ...,0
0,Si necesitas ir allá…,2026-03-16,[],{'track': {'trackName': 'Akaza Theme (Epic Ver...,0
...,...,...,...,...,...
13,RM&B,2025-08-28,[],{'track': {'trackName': 'Come Together (feat. ...,0
13,RM&B,2025-08-28,[],{'track': {'trackName': 'Don't Think They Know...,0
13,RM&B,2025-08-28,[],"{'track': {'trackName': 'Presiento', 'artistNa...",0
13,RM&B,2025-08-28,[],{'track': {'trackName': 'Quiéreme Mientras Se ...,0
13,RM&B,2025-08-28,[],{'track': {'trackName': 'Change Your Mind (fea...,0

In [27]:
exploded_df = exploded_df.reset_index(drop=True)
second_hand_exploded = pd.json_normalize(exploded_df['items'])
second_hand_exploded

,addedDate,track.trackName,track.artistName,track.albumName,track.trackUri
0,2026-02-05,DARK ARIA -ARISE-,SawanoHiroyuki[nZk],DARK ARIA -ARISE-,spotify:track:0BSGwoTRRZ0q58WB8RXLO3
1,2026-02-05,To the Infinity Castle - Muzan vs Hashira Them...,Diego Mitre,To the Infinity Castle - Muzan vs Hashira Them...,spotify:track:6vGFGjwN2UVK5dkgIBfjSL
2,2026-02-05,"Muzan vs Hashira ""Demon Slayer Hashira Trainin...",Pharozen,OrchestrAnime: Iconic OST Collection,spotify:track:2VIIZRueOhXTEEve60Wk9C
3,2026-02-05,Akaza Entrance Theme (Infinity Castle Movie: A...,Ashif N,Akaza Entrance Theme (Infinity Castle Movie: A...,spotify:track:19JAX2dcvQYOIVnf1TSMv0
4,2026-02-05,Akaza Theme (Epic Version) Demon Slayer Mugen ...,Ashif N,Akaza Theme (Epic Version) Demon Slayer Mugen ...,spotify:track:294bcBfD1xb1sQ0Jn78hNE
...,...,...,...,...,...
727,2024-06-28,Come Together (feat. H.E.R.),Chris Brown,Indigo,spotify:track:1IRU2kqvCmmySoB0ywJTmI
728,2024-06-28,Don't Think They Know (feat. Aaliyah),Chris Brown,X (Expanded Edition),spotify:track:3uVCPFmavlWGQUqeYh8HhR
729,2024-06-28,Presiento,Morat,Balas Perdidas,spotify:track:2V4hc5gplg7EXlrRUvD4rp
730,2024-06-28,Quiéreme Mientras Se Pueda,Manuel Turizo,Dopamina,spotify:track:1WH3iquIQXnSPwUzlROT8R
731,2025-08-28,Change Your Mind (feat. Shaboozey),Burna Boy,No Sign Of Weakness,spotify:track:6FXCkgH4PR9T15gx8osL5w

In [30]:
#exploded_df = exploded_df.join(second_hand_exploded)
exploded_df = exploded_df.drop(columns=['items','collaborators','numberOfFollowers'])
exploded_df

,name,lastModifiedDate,addedDate,track.trackName,track.artistName,track.albumName,track.trackUri
0,Si necesitas ir allá…,2026-03-16,2026-02-05,DARK ARIA -ARISE-,SawanoHiroyuki[nZk],DARK ARIA -ARISE-,spotify:track:0BSGwoTRRZ0q58WB8RXLO3
1,Si necesitas ir allá…,2026-03-16,2026-02-05,To the Infinity Castle - Muzan vs Hashira Them...,Diego Mitre,To the Infinity Castle - Muzan vs Hashira Them...,spotify:track:6vGFGjwN2UVK5dkgIBfjSL
2,Si necesitas ir allá…,2026-03-16,2026-02-05,"Muzan vs Hashira ""Demon Slayer Hashira Trainin...",Pharozen,OrchestrAnime: Iconic OST Collection,spotify:track:2VIIZRueOhXTEEve60Wk9C
3,Si necesitas ir allá…,2026-03-16,2026-02-05,Akaza Entrance Theme (Infinity Castle Movie: A...,Ashif N,Akaza Entrance Theme (Infinity Castle Movie: A...,spotify:track:19JAX2dcvQYOIVnf1TSMv0
4,Si necesitas ir allá…,2026-03-16,2026-02-05,Akaza Theme (Epic Version) Demon Slayer Mugen ...,Ashif N,Akaza Theme (Epic Version) Demon Slayer Mugen ...,spotify:track:294bcBfD1xb1sQ0Jn78hNE
...,...,...,...,...,...,...,...
727,RM&B,2025-08-28,2024-06-28,Come Together (feat. H.E.R.),Chris Brown,Indigo,spotify:track:1IRU2kqvCmmySoB0ywJTmI
728,RM&B,2025-08-28,2024-06-28,Don't Think They Know (feat. Aaliyah),Chris Brown,X (Expanded Edition),spotify:track:3uVCPFmavlWGQUqeYh8HhR
729,RM&B,2025-08-28,2024-06-28,Presiento,Morat,Balas Perdidas,spotify:track:2V4hc5gplg7EXlrRUvD4rp
730,RM&B,2025-08-28,2024-06-28,Quiéreme Mientras Se Pueda,Manuel Turizo,Dopamina,spotify:track:1WH3iquIQXnSPwUzlROT8R
731,RM&B,2025-08-28,2025-08-28,Change Your Mind (feat. Shaboozey),Burna Boy,No Sign Of Weakness,spotify:track:6FXCkgH4PR9T15gx8osL5w