In [1]:
import pandas as pd
import json

In [8]:
with open('C:\\Users\\JosephMoffatt\\OneDrive - Thought Logic\\Desktop\\GitHubRepos\\dataengineeringprojects\\DataEngineeringProjects\\auxdata\\Streaming_History_Audio_2022_1.json', 'r', encoding='utf-8') as f:
    extracted_fields = json.load(f)
    
print(extracted_fields[0])

{'ts': '2022-02-18T00:01:55Z', 'platform': 'iOS 15.2.1 (iPhone11,8)', 'ms_played': 960, 'conn_country': 'US', 'ip_addr': '174.215.150.184', 'master_metadata_track_name': 'Knock You Down', 'master_metadata_album_artist_name': 'Keri Hilson', 'master_metadata_album_album_name': 'In A Perfect World...', 'spotify_track_uri': 'spotify:track:58FUwmyGUqkt53YPUcm7cJ', 'episode_name': None, 'episode_show_name': None, 'spotify_episode_uri': None, 'audiobook_title': None, 'audiobook_uri': None, 'audiobook_chapter_uri': None, 'audiobook_chapter_title': None, 'reason_start': 'fwdbtn', 'reason_end': 'fwdbtn', 'shuffle': False, 'skipped': False, 'offline': False, 'offline_timestamp': None, 'incognito_mode': False}

In [7]:
df = pd.read_json('C:\\Users\\JosephMoffatt\\OneDrive - Thought Logic\\Desktop\\GitHubRepos\\dataengineeringprojects\\DataEngineeringProjects\\auxdata\\Streaming_History_Audio_2015.json')

df.head()

,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,...,audiobook_uri,audiobook_chapter_uri,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode
0,2015-01-20T22:06:44Z,"Android OS 4.4 API 19 (LGE, LGL34C)",22981,US,24.42.180.105,Trophies,Young Money,Rise Of An Empire,spotify:track:6HfOzLLjsaXsehIFEsrxTk,NaN,...,NaN,NaN,NaN,trackdone,fwdbtn,True,True,False,NaN,False
1,2015-01-20T22:06:45Z,"Android OS 4.4 API 19 (LGE, LGL34C)",2275,US,24.42.180.105,Roger That,Young Money,We Are Young Money,spotify:track:4UXpJDvdsfneLvT09oJocg,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,True,True,False,NaN,False
2,2015-01-20T22:06:48Z,"Android OS 4.4 API 19 (LGE, LGL34C)",0,US,24.42.180.105,BedRock,Young Money,We Are Young Money,spotify:track:3iL2l5gUqyPS6vDwJFgJTR,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,True,True,False,NaN,False
3,2015-01-20T22:06:48Z,"Android OS 4.4 API 19 (LGE, LGL34C)",0,US,24.42.180.105,We Alright,Young Money,Rise Of An Empire,spotify:track:7Ij7OiGCUjOkkqZ4ZTb76o,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,True,True,False,NaN,False
4,2015-01-20T22:06:48Z,"Android OS 4.4 API 19 (LGE, LGL34C)",0,US,24.42.180.105,Senile,Young Money,Rise Of An Empire,spotify:track:1paIMWwjQxE1GX3hqQ8IUW,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,True,True,False,NaN,False

In [ ]:
workingdf = df[['ts','ms_played','master_metadata_track_name','master_metadata_album_artist_name','master_metadata_album_album_name','spotify_track_uri','reason_start','reason_end']]
workingdf.head()

,ts,ms_played,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,reason_start,reason_end
0,2015-01-20T22:06:44Z,22981,Trophies,Young Money,Rise Of An Empire,spotify:track:6HfOzLLjsaXsehIFEsrxTk,trackdone,fwdbtn
1,2015-01-20T22:06:45Z,2275,Roger That,Young Money,We Are Young Money,spotify:track:4UXpJDvdsfneLvT09oJocg,fwdbtn,fwdbtn
2,2015-01-20T22:06:48Z,0,BedRock,Young Money,We Are Young Money,spotify:track:3iL2l5gUqyPS6vDwJFgJTR,fwdbtn,fwdbtn
3,2015-01-20T22:06:48Z,0,We Alright,Young Money,Rise Of An Empire,spotify:track:7Ij7OiGCUjOkkqZ4ZTb76o,fwdbtn,fwdbtn
4,2015-01-20T22:06:48Z,0,Senile,Young Money,Rise Of An Empire,spotify:track:1paIMWwjQxE1GX3hqQ8IUW,fwdbtn,fwdbtn

In [12]:
workingdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 370 entries, 0 to 369
Data columns (total 8 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   ts                                 370 non-null    object
 1   ms_played                          370 non-null    int64
 2   master_metadata_track_name         370 non-null    object
 3   master_metadata_album_artist_name  370 non-null    object
 4   master_metadata_album_album_name   370 non-null    object
 5   spotify_track_uri                  370 non-null    object
 6   reason_start                       370 non-null    object
 7   reason_end                         370 non-null    object
dtypes: int64(1), object(7)
memory usage: 23.3+ KB

In [8]:
len(workingdf)

370

In [9]:
df_two = pd.read_json('C:\\Users\\JosephMoffatt\\OneDrive - Thought Logic\\Desktop\\GitHubRepos\\dataengineeringprojects\\DataEngineeringProjects\\auxdata\\Streaming_History_Audio_2022_1.json')

df_two.head()

,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,...,audiobook_uri,audiobook_chapter_uri,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode
0,2022-02-18T00:01:55Z,"iOS 15.2.1 (iPhone11,8)",960,US,174.215.150.184,Knock You Down,Keri Hilson,In A Perfect World...,spotify:track:58FUwmyGUqkt53YPUcm7cJ,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,False,False,False,NaN,False
1,2022-02-18T00:01:56Z,"iOS 15.2.1 (iPhone11,8)",1216,US,174.215.150.184,Your Love,Nicki Minaj,Pink Friday,spotify:track:1w6kG4Rc29m5EherbvpkF5,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,False,False,False,NaN,False
2,2022-02-18T00:01:57Z,"iOS 15.2.1 (iPhone11,8)",960,US,174.215.150.184,Bartier Cardi (feat. 21 Savage),Cardi B,Invasion of Privacy,spotify:track:0dIoGTQXDh1wVnhIiSyYEa,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,False,False,False,NaN,False
3,2022-02-18T00:02:32Z,"iOS 15.2.1 (iPhone11,8)",34517,US,174.215.150.184,My Type,Saweetie,ICY,spotify:track:5KBARWIxeMGkvUax9VtVC9,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,False,False,False,NaN,False
4,2022-02-18T00:02:33Z,"iOS 15.2.1 (iPhone11,8)",1173,US,174.215.150.184,I Don't Fuck With You,Big Sean,Dark Sky Paradise,spotify:track:7FYH5AW3bVfZHJIQpq3UOA,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,False,False,False,NaN,False

In [11]:
df_three = pd.read_json('C:\\Users\\JosephMoffatt\\OneDrive - Thought Logic\\Desktop\\GitHubRepos\\dataengineeringprojects\\DataEngineeringProjects\\auxdata\\Streaming_History_Audio_2026.json')

df_three.head()

,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,...,audiobook_uri,audiobook_chapter_uri,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode
0,2026-01-22T14:53:57Z,ios,353152,US,2601:c6:d37c:560:e863:19eb:1b1a:c021,NADIE SABE,Bad Bunny,nadie sabe lo que va a pasar mañana,spotify:track:23d8v6tU6lR77pFKsApMtF,None,...,NaN,NaN,NaN,clickrow,unexpected-exit-while-paused,False,False,False,1769084484,False
1,2026-01-22T14:57:42Z,ios,185830,US,2601:c6:d37c:560:e863:19eb:1b1a:c021,Long Journey,Rod Wave,Nostalgia,spotify:track:1xnAVO60FwWTRa7LJPoNKG,None,...,NaN,NaN,NaN,clickrow,trackdone,False,False,False,1769093676,False
2,2026-01-22T14:57:57Z,ios,17209,US,2601:c6:d37c:560:e863:19eb:1b1a:c021,Love For A Thug,Rod Wave,Nostalgia,spotify:track:694k4TfDqOqmhebj79li54,None,...,NaN,NaN,NaN,trackdone,fwdbtn,False,True,False,1769093858,False
3,2026-01-22T14:57:59Z,ios,1834,US,2601:c6:d37c:560:e863:19eb:1b1a:c021,Favorite Song,Toosii,NAUJOUR,spotify:track:5Bvhk3wx42kkDEggSQIwqL,None,...,NaN,NaN,NaN,fwdbtn,fwdbtn,False,True,False,1769093877,False
4,2026-01-22T14:58:03Z,ios,3878,US,2601:c6:d37c:560:e863:19eb:1b1a:c021,City of God (feat. Chris Brown),Tee Grizzley,Tee's Coney Island,spotify:track:0PmM2q7VEi2Sw6IO9CLn79,None,...,NaN,NaN,NaN,fwdbtn,endplay,False,True,False,1769093879,False