### New Dataset Exploration

In [1]:
import pandas as pd

In [2]:
#!pip install kagglehub

In [3]:
import kagglehub

In [4]:
# Download latest version
path = kagglehub.dataset_download("melissamonfared/spotify-tracks-attributes-and-popularity")

print("Path to dataset files:", path)

# Now just use that path to load your data
df = pd.read_csv(f"{path}\dataset.csv")

<>:7: SyntaxWarning: invalid escape sequence '\d'
<>:7: SyntaxWarning: invalid escape sequence '\d'
C:\Users\moffa\AppData\Local\Temp\ipykernel_32344\234194689.py:7: SyntaxWarning: invalid escape sequence '\d'
  df = pd.read_csv(f"{path}\dataset.csv")

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.11), please consider upgrading to the latest version (0.4.1).
Path to dataset files: C:\Users\moffa\.cache\kagglehub\datasets\melissamonfared\spotify-tracks-attributes-and-popularity\versions\1

In [5]:
df

,index,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,...,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,...,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,...,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,...,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,...,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

In [12]:
df['track_genre'].unique()

array(['acoustic', 'afrobeat', 'alt-rock', 'alternative', 'ambient',
       'anime', 'black-metal', 'bluegrass', 'blues', 'brazil',
       'breakbeat', 'british', 'cantopop', 'chicago-house', 'children',
       'chill', 'classical', 'club', 'comedy', 'country', 'dance',
       'dancehall', 'death-metal', 'deep-house', 'detroit-techno',
       'disco', 'disney', 'drum-and-bass', 'dub', 'dubstep', 'edm',
       'electro', 'electronic', 'emo', 'folk', 'forro', 'french', 'funk',
       'garage', 'german', 'gospel', 'goth', 'grindcore', 'groove',
       'grunge', 'guitar', 'happy', 'hard-rock', 'hardcore', 'hardstyle',
       'heavy-metal', 'hip-hop', 'honky-tonk', 'house', 'idm', 'indian',
       'indie-pop', 'indie', 'industrial', 'iranian', 'j-dance', 'j-idol',
       'j-pop', 'j-rock', 'jazz', 'k-pop', 'kids', 'latin', 'latino',
       'malay', 'mandopop', 'metal', 'metalcore', 'minimal-techno', 'mpb',
       'new-age', 'opera', 'pagode', 'party', 'piano', 'pop-film', 'pop',
       'power-pop', 'progressive-house', 'psych-rock', 'punk-rock',
       'punk', 'r-n-b', 'reggae', 'reggaeton', 'rock-n-roll', 'rock',
       'rockabilly', 'romance', 'sad', 'salsa', 'samba', 'sertanejo',
       'show-tunes', 'singer-songwriter', 'ska', 'sleep', 'songwriter',
       'soul', 'spanish', 'study', 'swedish', 'synth-pop', 'tango',
       'techno', 'trance', 'trip-hop', 'turkish', 'world-music'],
      dtype=object)

In [13]:
df_filtered = df[df['track_genre'] == 'spanish']
df_filtered

,index,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
104000,104000,5ZEQjTroORCu6uWvZrdeNc,Cecilia Krull,My Life Is Going On (Música Original De La Ser...,My Life Is Going On (Música Original De La Ser...,62,214200,False,0.427,0.647,...,-8.944,0,0.0353,0.102000,0.000002,0.1330,0.2980,99.753,4,spanish
104001,104001,0hjpo40L9XPirSdaJZOGB2,Lola Indigo;Maria Becerra,Bájale como 7500,DISCOTEKA,2,174801,False,0.795,0.854,...,-5.462,1,0.0444,0.162000,0.000001,0.0923,0.5490,105.992,4,spanish
104002,104002,5QqSYrL0dN5fvwQYEfltOa,Lola Indigo;Maria Becerra,El perreo es el futuro,DISCOTEKA,0,174801,False,0.795,0.854,...,-5.462,1,0.0444,0.162000,0.000001,0.0923,0.5490,105.992,4,spanish
104003,104003,7sNBIIStlc2ifqAkdySXLM,Aitana;Sebastian Yatra,Dulce Balada,Corazón Sin Vida,0,181978,False,0.480,0.572,...,-4.013,1,0.0412,0.169000,0.000000,0.0711,0.4520,89.890,4,spanish
104004,104004,6QdFtyixbbTami8OPxtJuw,Lola Indigo;Maria Becerra,Clásicos de ahora: Perreo,DISCOTEKA,0,174801,False,0.795,0.854,...,-5.462,1,0.0444,0.162000,0.000001,0.0923,0.5490,105.992,4,spanish
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104995,104995,6uNFIMxbvOwQku3vew2kZ3,El Noi del Sucre,A Mi Manera Vol. 2 (Leyendas de un Desconocido),El Día Que el Pueblo Tomó la Palabra,25,355311,False,0.323,0.997,...,-2.245,1,0.4580,0.012500,0.000004,0.1240,0.1600,176.044,4,spanish
104996,104996,5AFINiJKbB8SDzBz287Q0h,Mägo de Oz,Folktergeist,Hasta Que Tu Muerte Nos Separe,26,494259,False,0.307,0.850,...,-6.056,1,0.1050,0.000677,0.000012,0.7730,0.3860,160.084,4,spanish
104997,104997,5OH2gnAyEY5SjrjzbNMVkZ,Lola Ponce;Giò Di Tonno;Richard Cocciante,Notre Dame de Paris - Live Arena Di Verona 200...,"Ali In Gabbia, Occhi Selvaggi - Live",26,186786,False,0.545,0.311,...,-12.695,0,0.0303,0.610000,0.000005,0.3850,0.0646,105.063,4,spanish
104998,104998,5ZfnMTxigllIu1aGgyfYWF,"Ana Torroja;Sasha, Benny y Erik",Conexión (En Vivo),50 Palabras 60 Palabras o 100 - En Vivo,27,237813,False,0.413,0.688,...,-8.694,1,0.0350,0.021500,0.000201,0.9730,0.2690,104.566,4,spanish
104999,104999,5C2nrrB6uVh4vo6Z6zKTNg,La Quinta Estacion,Directo Desde Madrid,Algo Más (Versión Acústica) [Directo Madrid] -...,26,467333,False,0.448,0.633,...,-7.978,0,0.0832,0.016800,0.000022,0.9820,0.2650,149.810,4,spanish

In [6]:
# Download latest version
path = kagglehub.dataset_download("brunoalarcon123/top-200-spotify-songs-dataset")

print("Path to dataset files:", path)
df = pd.read_csv(f"{path}\Spotify_Dataset_V3.csv")

<>:5: SyntaxWarning: invalid escape sequence '\S'
<>:5: SyntaxWarning: invalid escape sequence '\S'
C:\Users\moffa\AppData\Local\Temp\ipykernel_32344\136166108.py:5: SyntaxWarning: invalid escape sequence '\S'
  df = pd.read_csv(f"{path}\Spotify_Dataset_V3.csv")

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.11), please consider upgrading to the latest version (0.4.1).
Path to dataset files: C:\Users\moffa\.cache\kagglehub\datasets\brunoalarcon123\top-200-spotify-songs-dataset\versions\4

C:\Users\moffa\AppData\Local\Temp\ipykernel_32344\136166108.py:5: SyntaxWarning: invalid escape sequence '\S'
  df = pd.read_csv(f"{path}\Spotify_Dataset_V3.csv")

ParserError: Error tokenizing data. C error: Expected 2 fields in line 22, saw 3

In [8]:
#import kagglehub
#from kagglehub import KaggleDatasetAdapter

In [9]:
path = kagglehub.dataset_download('bricevergnou/spotify-recommendation')
print("Path to dataset files:", path)
df = pd.read_csv(f"{path}\data.csv")

<>:3: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\d'
C:\Users\moffa\AppData\Local\Temp\ipykernel_32344\3482809069.py:3: SyntaxWarning: invalid escape sequence '\d'
  df = pd.read_csv(f"{path}\data.csv")

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.11), please consider upgrading to the latest version (0.4.1).
Path to dataset files: C:\Users\moffa\.cache\kagglehub\datasets\bricevergnou\spotify-recommendation\versions\2

In [10]:
df

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,liked
0,0.803,0.6240,7,-6.764,0,0.0477,0.4510,0.000734,0.1000,0.6280,95.968,304524,4,0
1,0.762,0.7030,10,-7.951,0,0.3060,0.2060,0.000000,0.0912,0.5190,151.329,247178,4,1
2,0.261,0.0149,1,-27.528,1,0.0419,0.9920,0.897000,0.1020,0.0382,75.296,286987,4,0
3,0.722,0.7360,3,-6.994,0,0.0585,0.4310,0.000001,0.1230,0.5820,89.860,208920,4,1
4,0.787,0.5720,1,-7.516,1,0.2220,0.1450,0.000000,0.0753,0.6470,155.117,179413,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,0.166,0.0551,9,-19.494,0,0.0520,0.9760,0.635000,0.1190,0.1430,176.616,206520,3,0
191,0.862,0.6240,3,-11.630,1,0.0565,0.0192,0.000153,0.0465,0.8820,124.896,254240,4,0
192,0.499,0.3510,9,-11.509,0,0.0448,0.9510,0.000099,0.1180,0.6160,90.664,235947,4,0
193,0.574,0.7290,10,-5.838,0,0.0965,0.0406,0.000004,0.1940,0.4130,110.547,190239,5,1
194,0.747,0.6660,11,-7.845,1,0.1970,0.1300,0.000000,0.3600,0.5310,77.507,177213,4,1

In [ ]:
#songs_with_attributes_and_lyrics.csv
#songs_with_lyrics_and_timestamps.csv

In [12]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("bwandowando/spotify-songs-with-attributes-and-lyrics")

print("Path to dataset files:", path)
df = pd.read_csv(f"{path}\songs_with_attributes_and_lyrics.csv")

<>:7: SyntaxWarning: invalid escape sequence '\s'
<>:7: SyntaxWarning: invalid escape sequence '\s'
C:\Users\moffa\AppData\Local\Temp\ipykernel_32344\506604683.py:7: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv(f"{path}\songs_with_attributes_and_lyrics.csv")

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.11), please consider upgrading to the latest version (0.4.1).
Path to dataset files: C:\Users\moffa\.cache\kagglehub\datasets\bwandowando\spotify-songs-with-attributes-and-lyrics\versions\19

In [15]:
df

,id,name,album_name,artists,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,lyrics
0,0Prct5TDjAnEgIqbxcldY9,!,UNDEN!ABLE,['HELLYEAH'],0.415,0.6050,7,-11.157,1,0.0575,0.00116,0.838000,0.4710,0.1930,100.059,79500.0,"He said he came from Jamaica,\n he owned a cou..."
1,2ASl4wirkeYm3OWZxXKYuq,!!,NaN,Yxngxr1,0.788,0.6480,7,-9.135,0,0.3150,0.90000,0.000000,0.1760,0.2870,79.998,114000.0,"Fucked a bitch, now she running with my kids\n..."
2,69lcggVPmOr9cvPx9kLiiN,!!! - Interlude,Where I Belong EP,['Glowie'],0.000,0.0354,7,-20.151,0,0.0000,0.90800,0.000000,0.4790,0.0000,0.000,11413.0,"Oh, my God, I'm going crazy\n"
3,4U7dlZjg1s9pjdppqZy0fm,!!De Repente!!,Un Palo Al Agua (20 Grandes Canciones),['Rosendo'],0.657,0.8820,5,-6.340,1,0.0385,0.00740,0.000013,0.0474,0.9390,123.588,198173.0,Continuamente se extraña la gente si no puede ...
4,4v1IBp3Y3rpkWmWzIlkYju,!!De Repente!!,Fuera De Lugar,['Rosendo'],0.659,0.8930,5,-8.531,1,0.0411,0.09220,0.000019,0.0534,0.9510,123.600,199827.0,Continuamente se extraña la gente si no puede ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955315,4zMgP1HJazJJdEf6AiG8M6,NaN,NaN,['SuperKek'],0.456,0.4820,8.0,-11.199,1.0,0.0504,0.02970,0.000000,0.1110,0.0352,71.455,281962.0,And all I am is a man\n I want the world in my...
955316,5N0MQFuudsDIQpapNI5MHM,NaN,NaN,['Prasewon'],0.543,0.2900,2.0,-14.526,0.0,0.1580,0.66700,0.015100,0.1470,0.3640,172.118,87980.0,"I think I, I think I finally\n Found a way to ..."
955317,5R8xbq4SXB5Cc62Lu7cW4y,NaN,NaN,['SoulkaOuter'],0.696,0.4440,10.0,-12.894,0.0,0.0593,0.59300,0.000740,0.2130,0.3070,105.953,129370.0,Tak dayte patsanam poschitat' poteri\n Summy n...
955318,5cjecvX0CmC9gK0Laf5EMQ,NaN,NaN,NaN,0.678,0.6590,11,-5.364,0,0.3190,0.05340,0.000000,0.5530,0.1910,146.153,202235.0,"Ave Maria, Ave Maria\n ♪\n Ich bin in der Beto..."
955319,7gi1gHXljCBwbBAF7Rhdwk,NaN,NaN,['Jenkiss'],0.615,0.6010,9.0,-9.834,0.0,0.0613,0.01650,0.000000,0.1990,0.3850,135.207,113128.0,"Я был прав, но не счастлив\n Разбуди меня огне..."

In [14]:
df['lyrics'][0]

'He said he came from Jamaica,\n he owned a couple acres A couple fake visas \'cause he never got his\n papers Gave up on love fucking with them heart breakers But he was\n getting money with the movers and the shakers He was mixed with a\n couple things, bald like a couple rings Bricks in the condo and grams\n to sing-sing Left arm,\n baby mother tatted 5-year bid up North when they ratted Anyway I felt\n him, helped him, put him on lock,\n seat-belt him Took him out to Belgium, welcome Bitches this pretty,\n that\'s seldom This box better than the box he was held in I\'m Momma\n Dee in that order, I call him Daddy like daughters He like it when I\n get drunk, but I like it when he be sober That\'s top of the toppa,\n I never fuck with beginners I let him play with my pussy then lick it\n off of his fingers, I\'m in the zone They holler at me, but it\'s you,\n you, this ain\'t high school Me and my crew,\n we can slide through Give it to you whenever you want,\n whip it whenever you want Baby it\'s yours Anywhere, everywhere,\n baby it\'s your world, ain\'t it?\n (alright) Baby it\'s your world, ain\'t it?\n Uh, she got a nigga at home and one on the side Best friend is a\n dyke, they fucked around a few times Her and her momma alike,\n so all they do is fight I tell her "make me some money",\n she tell me "make me a wife" I tell that bitch "you crazy,\n fuck wrong with you?" And excuse my French,\n but I\'m a long kisser And then she try to tell me I\'m the only one\n that\'s hitting And I say "what about them niggas?" She say:\n "what about them niggas?" You right, what you doing tonight?\n Put on something tight, don\'t judge me,\n I\'d get life She love me like a brother,\n but fuck me like a husband Pussy like a oven,\n too hot to put my tongue in All I had to do is rub it,\n the genie out the bottle Pussy so wet,\n I\'mma need goggles She tell me that\'s it\'s mine,\n I tell her "stop lying, mine and who else?\n " She say worry about yourself Lil Tune They holler at me,\n but it\'s you, you, this ain\'t high school Me and my crew,\n we can slide through Give it to you whenever you want,\n whip it whenever you want Baby it\'s yours\n Anywhere, everywhere, baby it\'s your world, ain\'t it?\n Baby it\'s your world, ain\'t it?\n I know you want it boy, I see you tryin\' Just keep on pushing,\n I\'mma let you slide in Just close your eyes and,\n this horizon It\'s ready, come get you some Yeah, yeah, yeah, yeah'

In [17]:
print(path)

C:\Users\moffa\.cache\kagglehub\datasets\bwandowando\spotify-songs-with-attributes-and-lyrics\versions\19

In [18]:
df2 = pd.read_csv(f"{path}\songs_with_lyrics_and_timestamps.csv")
df2

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\moffa\AppData\Local\Temp\ipykernel_32344\3272088902.py:1: SyntaxWarning: invalid escape sequence '\s'
  df2 = pd.read_csv(f"{path}\songs_with_lyrics_and_timestamps.csv")

,id,startTimeMs,words
0,000TJYlDLPM01ebX8QtIUS,42710,Siento escapar mi vida
1,000TJYlDLPM01ebX8QtIUS,70350,"que triste se va, triste termina."
2,000TJYlDLPM01ebX8QtIUS,74780,Intento olvidar tu gran herida
3,000TJYlDLPM01ebX8QtIUS,87530,"que siendo mortal, es también mía."
4,000TJYlDLPM01ebX8QtIUS,94990,Tal vez podré algún día surcar otra vez
...,...,...,...
36519087,7zxRMhXxJMQCeDDg0rKAVo,155660,"(Nah, nah-nah-nah, nah-nah-nah)"
36519088,7zxRMhXxJMQCeDDg0rKAVo,157800,"I just took that chick, and I know you feelin'..."
36519089,7zxRMhXxJMQCeDDg0rKAVo,163980,"She just want a nigga like me, you feelin' som..."
36519090,7zxRMhXxJMQCeDDg0rKAVo,170160,"She just want a nigga like me, I play no games"
36519091,7zxRMhXxJMQCeDDg0rKAVo,175290,NaN