# Data Transformations file

In [1]:
import pandas as pd
import json
import kagglehub
from datetime import datetime
from sklearn.preprocessing import LabelEncoder
import mysql.connector
from sqlalchemy import create_engine

### Streaming Library Audio

In [2]:
def streaming_library_json():
    base_string_one = 'Data/StreamingHistory_music_'
    base_string_two = '.json'
    df_list = []
    for i in range(0,6):
        new_string = base_string_one+str(i)+base_string_two
        print(new_string)
        current_df = pd.read_json(new_string)
        df_list.append(current_df)
    
    combined_df = pd.concat(df_list, ignore_index=True)
    combined_df
    combined_df[['Date','International Time']] = combined_df['endTime'].str.split(" ",expand = True)
    combined_df[['Year','Month','Day']] = combined_df['Date'].str.split("-",expand = True)
    combined_df = combined_df.astype(str)
    return combined_df

In [3]:
combined_df = streaming_library_json()
combined_df

Data/StreamingHistory_music_0.json
Data/StreamingHistory_music_1.json
Data/StreamingHistory_music_2.json
Data/StreamingHistory_music_3.json
Data/StreamingHistory_music_4.json
Data/StreamingHistory_music_5.json

,endTime,artistName,trackName,msPlayed,Date,International Time,Year,Month,Day
0,2025-01-11 00:27,Kendrick Lamar,Not Like Us,93019,2025-01-11,00:27,2025,01,11
1,2025-01-11 16:27,Tempo,Happy Birthday,60487,2025-01-11,16:27,2025,01,11
2,2025-01-11 16:28,Marc Anthony,Vivir Mi Vida,79180,2025-01-11,16:28,2025,01,11
3,2025-01-11 16:30,Rauw Alejandro,Todo De Ti,99079,2025-01-11,16:30,2025,01,11
4,2025-01-11 16:33,Cali Y El Dandee,Por Fin Te Encontré,165326,2025-01-11,16:33,2025,01,11
...,...,...,...,...,...,...,...,...,...
49977,2026-01-10 19:51,BCA,Se Descargo el Amor,192929,2026-01-10,19:51,2026,01,10
49978,2026-01-10 19:53,MC Sencillo,Cara de Santita,145580,2026-01-10,19:53,2026,01,10
49979,2026-01-10 21:17,El Roockie,Atrás,211954,2026-01-10,21:17,2026,01,10
49980,2026-01-10 23:48,El Roockie,Atrás,35526,2026-01-10,23:48,2026,01,10
49981,2026-01-10 23:53,Real Phantom,Plena Monstruosa,274051,2026-01-10,23:53,2026,01,10

### My Library

In [4]:
def my_library():
    with open('Data/YourLibrary.json','r', encoding='utf-8') as f:
        data = json.load(f)
    keylist = list(data.keys())
    albumsdf = pd.DataFrame(columns=data['albums'][0].keys())
    albumsdf = pd.concat([albumsdf, pd.DataFrame(data['albums'])], ignore_index = True)
    return albumsdf

In [5]:
albums_df = my_library()
albums_df

,artist,album,uri
0,Jason Derulo,Talk Dirty,spotify:album:4PeZu0It7qVrTG40t3HM9A
1,Various Artists,Neighborhood Watch Vol.1,spotify:album:1nv0qL4lF9KG7tAJRGPOAy
2,NF,The Search,spotify:album:6w8mGg73sQl4QJEhpDUvpI
3,Lil Uzi Vert,Lil Uzi Vert vs. The World,spotify:album:7mgdTKTCdfnLoa1HXHvLYM
4,Lil Baby,Drip Too Hard,spotify:album:0LfKQSbicPG4QTTVkS0fes
...,...,...,...
165,Drake,So Far Gone,spotify:album:61NNWRxokNUQx0aYysBL76
166,Carnage,Bricks (feat. Migos),spotify:album:0ixvhVQx1kaTUFSX086V9E
167,Hillsong Young & Free,Love Won’t Let Me Down,spotify:album:0GpdJt8PyFiCeShU4mHjEX
168,Juice WRLD,Legends Never Die,spotify:album:1R6vbGGXSEZZmTGn7ewwRL
169,Patrik Pietschmann,The Chronicles of Narnia Main Theme,spotify:album:1CO5zsI6JYvU9yDY6sz3v5

### Wrapped Previous Year

In [6]:
def wrapped_previous_year(year:int):
    with open('Data/Wrapped'+str(year)+'.json', 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    top_artists = pd.DataFrame(data['topArtists'])
    top_artists['year'] = year
    top_artists = top_artists[:1]
    expanded = pd.json_normalize(top_artists['topArtists'])
    top_artists_df = pd.concat([top_artists.drop(columns=['topArtists']), expanded], axis=1)
    top_artists_df

    podcastdf = pd.DataFrame(columns=data['topPodcasts'].keys())
    podcastdf.loc[len(podcastdf)] = data['topPodcasts']
    podcastdf
    podcastdf = podcastdf.explode('topPodcastsUri')
    podcastdf
    
    yearlymetricsdf = pd.DataFrame(columns=data['yearlyMetrics'].keys())
    yearlymetricsdf.loc[len(yearlymetricsdf)] = data['yearlyMetrics']
    yearlymetricsdf

    evolutiondf = pd.DataFrame(columns=data['musicEvolution']['eras'][0].keys())
    evolutiondf = pd.concat([evolutiondf, pd.DataFrame(data['musicEvolution']['eras'])], ignore_index = True) #need to explode tracks column
    evolutiondf = evolutiondf.explode(['pivotalArtists', 'tracks'])
    evolutiondf = evolutiondf.explode(['tracks'])

    return (top_artists_df,podcastdf,yearlymetricsdf,evolutiondf)

In [7]:
previous_year = datetime.now().year - 1
previous_year

2025

In [8]:
try:
    top_artists, podcastdf, yearlymetricsdf,evolutiondf = wrapped_previous_year(2024)
except FileNotFoundError:
    print("No data for the year entered")

In [9]:
top_artists

,numUniqueArtists,topArtistMilliseconds,topArtistFanPercentage,year,artistUri
0,1154,615182194,0.000094,2024,spotify:artist:7bXgB6jMjp9ATFy66eO08Z

In [10]:
podcastdf

,topPodcastsUri,topPodcastMilliseconds,topPodcastPercentage,totalPodcastMilliseconds
0,spotify:show:2KYyAGSPNJKUKCuqURpDuV,4303258,0.0,11860304

In [11]:
yearlymetricsdf

,totalMsListened,mostListenedDay,mostListenedDayMinutes,percentGreaterThanWorldwideUsers
0,2645268134,2024-07-13,615.8227,94.2563

In [12]:
evolutiondf

,key,peakMonth,color,genre,mood,descriptor,pivotalArtists,tracks
0,0,4,red-green,rap,boujee,football,spotify:artist:0ErzCpIMyLcjPiwT4elrtZ,trackName
0,0,4,red-green,rap,boujee,football,spotify:artist:0ErzCpIMyLcjPiwT4elrtZ,trackUri
0,0,4,red-green,rap,boujee,football,spotify:artist:6qxpnaukVayrQn6ViNvu9I,trackName
0,0,4,red-green,rap,boujee,football,spotify:artist:6qxpnaukVayrQn6ViNvu9I,trackUri
0,0,4,red-green,rap,boujee,football,spotify:artist:3TVXtAsR1Inumwj472S9r4,trackName
0,0,4,red-green,rap,boujee,football,spotify:artist:3TVXtAsR1Inumwj472S9r4,trackUri
1,1,5,green-blue,r&b,mood music,throwback pop,spotify:artist:7bXgB6jMjp9ATFy66eO08Z,trackName
1,1,5,green-blue,r&b,mood music,throwback pop,spotify:artist:7bXgB6jMjp9ATFy66eO08Z,trackUri
1,1,5,green-blue,r&b,mood music,throwback pop,spotify:artist:23zg3TcAtWQy7J6upgbUnj,trackName
1,1,5,green-blue,r&b,mood music,throwback pop,spotify:artist:23zg3TcAtWQy7J6upgbUnj,trackUri
1,1,5,green-blue,r&b,mood music,throwback pop,spotify:artist:21E3waRsmPlU7jZsS13rcj,trackName
1,1,5,green-blue,r&b,mood music,throwback pop,spotify:artist:21E3waRsmPlU7jZsS13rcj,trackUri
2,2,6,red-green,latin dance,entertaining,hollywood,spotify:artist:4V8Sr092TqfHkfAA5fXXqG,trackName
2,2,6,red-green,latin dance,entertaining,hollywood,spotify:artist:4V8Sr092TqfHkfAA5fXXqG,trackUri
2,2,6,red-green,latin dance,entertaining,hollywood,spotify:artist:7qG3b048QCHVRO5Pv1T5lw,trackName
2,2,6,red-green,latin dance,entertaining,hollywood,spotify:artist:7qG3b048QCHVRO5Pv1T5lw,trackUri
2,2,6,red-green,latin dance,entertaining,hollywood,spotify:artist:1vyhD5VmyZ7KMfW5gqLgo5,trackName
2,2,6,red-green,latin dance,entertaining,hollywood,spotify:artist:1vyhD5VmyZ7KMfW5gqLgo5,trackUri

### Streaming History Podcast

In [13]:
def streaming_history_podcast():
    with open('Data/StreamingHistory_podcast_0.json', 'r', encoding='utf-8') as f:
        data = json.load(f)

    podcastsdf = pd.DataFrame(columns=data[0].keys())

    podcastsdf = pd.concat([podcastsdf, pd.DataFrame(data)], ignore_index = True)
    return podcastsdf

In [14]:
stream_history_podcast = streaming_history_podcast()
stream_history_podcast

,endTime,podcastName,episodeName,msPlayed
0,2025-01-14 16:45,Immersive Spanish,Immersive Spanish con Kav - Episode 1 - Barcel...,490660
1,2025-01-14 16:47,Chill Spanish Listening Practice,Episode zero,164188
2,2025-01-14 16:53,Chill Spanish Listening Practice,"#1 ""La familia""",275338
3,2025-01-14 16:58,Chill Spanish Listening Practice,"#2 ""El trabajo""",294196
4,2025-01-14 16:59,Chill Spanish Listening Practice,"#3 ""La Música""",2634
...,...,...,...,...
506,2025-12-19 19:38,Cerealistico,#1 Edison Broce,695693
507,2025-12-22 17:41,Clarissima,¿Boza cobra medio millón por show? ¡Él mismo r...,2653362
508,2025-12-22 17:43,Clarissima,¡El Gordo y La Flaca al descubierto!,91738
509,2025-12-26 16:00,Sin Traducir Podcast,Ep. 03 - Idiomas y ser bilingüe,3258867
510,2025-12-26 16:05,Sin Traducir Podcast,"Ep. 04 - Consejos de hermana mayor, qué les di...",258000

## Outside DataSets

### Spotify Tracks Attributes And Popularity

In [15]:
def kaggle_datasets():
    popularity = tracks_attributes_and_popularity()
    attributes,lyrics = songs_with_attributes_and_lyrics()
    return popularity,attributes,lyrics

In [16]:
def tracks_attributes_and_popularity():
    # Download latest version
    path = kagglehub.dataset_download("melissamonfared/spotify-tracks-attributes-and-popularity")
    
    print("Path to dataset files:", path)
    
    # Now just use that path to load your data
    df = pd.read_csv(f"{path}\dataset.csv")
    return df

<>:8: SyntaxWarning: invalid escape sequence '\d'
<>:8: SyntaxWarning: invalid escape sequence '\d'
C:\Users\moffa\AppData\Local\Temp\ipykernel_2796\2639495653.py:8: SyntaxWarning: invalid escape sequence '\d'
  df = pd.read_csv(f"{path}\dataset.csv")

### Songs with Attributes and Lyrics

In [17]:
def songs_with_attributes_and_lyrics():
    # Download latest version
    path = kagglehub.dataset_download("bwandowando/spotify-songs-with-attributes-and-lyrics")
    
    print("Path to dataset files:", path)
    df = pd.read_csv(f"{path}\songs_with_attributes_and_lyrics.csv")
    df2 = pd.read_csv(f"{path}\songs_with_lyrics_and_timestamps.csv")

    return df,df2

<>:6: SyntaxWarning: invalid escape sequence '\s'
<>:7: SyntaxWarning: invalid escape sequence '\s'
<>:6: SyntaxWarning: invalid escape sequence '\s'
<>:7: SyntaxWarning: invalid escape sequence '\s'
C:\Users\moffa\AppData\Local\Temp\ipykernel_2796\2611942565.py:6: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv(f"{path}\songs_with_attributes_and_lyrics.csv")
C:\Users\moffa\AppData\Local\Temp\ipykernel_2796\2611942565.py:7: SyntaxWarning: invalid escape sequence '\s'
  df2 = pd.read_csv(f"{path}\songs_with_lyrics_and_timestamps.csv")

In [18]:
popularity,attributes,lyrics = kaggle_datasets()

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.11), please consider upgrading to the latest version (1.0.0).
Path to dataset files: C:\Users\moffa\.cache\kagglehub\datasets\melissamonfared\spotify-tracks-attributes-and-popularity\versions\1
Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.11), please consider upgrading to the latest version (1.0.0).
Path to dataset files: C:\Users\moffa\.cache\kagglehub\datasets\bwandowando\spotify-songs-with-attributes-and-lyrics\versions\19

In [19]:
popularity.columns

Index(['index', 'track_id', 'artists', 'album_name', 'track_name',
       'popularity', 'duration_ms', 'explicit', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature',
       'track_genre'],
      dtype='object')

In [20]:
attributes.columns

Index(['id', 'name', 'album_name', 'artists', 'danceability', 'energy', 'key',
       'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness',
       'liveness', 'valence', 'tempo', 'duration_ms', 'lyrics'],
      dtype='object')

In [21]:
lyrics.columns

Index(['id', 'startTimeMs', 'words'], dtype='object')

## UnWrapping

In [22]:
def get_song_metrics(popularity: pd.DataFrame,combined_df: pd.DataFrame, threshold: int):
    
    result = pd.merge(
    combined_df, 
    popularity, 
    left_on='trackName',
    right_on='track_name',  
    how='inner'
    )
    
    results_deduped = result.drop_duplicates(['trackName'])
    results_deduped['msPlayed'] = results_deduped['msPlayed'].astype(int)
    results_deduped = results_deduped[results_deduped['msPlayed'] > threshold]
    results_deduped = results_deduped.reset_index()
    results_deduped = results_deduped.drop('level_0',axis = 1)

    le = LabelEncoder()
    le_two = LabelEncoder()

    results_deduped['encoded_genre'] = le.fit_transform(results_deduped['track_genre'])
    results_deduped['encoded_artists'] = le_two.fit_transform(results_deduped['artistName'])

    return results_deduped,le,le_two

In [23]:
result_df,le,le_two = get_song_metrics(popularity,combined_df,10000)

C:\Users\moffa\AppData\Local\Temp\ipykernel_2796\454950083.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results_deduped['msPlayed'] = results_deduped['msPlayed'].astype(int)

#### Settings Bins Within The Data

In [24]:
def scaling_and_create_bins(df: pd.DataFrame,le,le_two):
    df_analysis = df.drop(['endTime','artistName','trackName','Date','International Time','index','track_id','artists','album_name','track_name','track_genre'],axis = 1)
    df_analysis = df_analysis
    columns_to_be_scaled = ['danceability', 'energy', 'key',
       'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness',
       'liveness', 'valence', 'tempo']

    df_analysis[columns_to_be_scaled] = df_analysis[columns_to_be_scaled] * 1000

    list_of_df_mean = []
    list_of_df_sum = []
    list_of_df_sd = []
    
    for i in columns_to_be_scaled:
        holder_df_mean = df_analysis.groupby('Month')[i].mean()
        holder_df_mean = pd.DataFrame(holder_df_mean)
        list_of_df_mean.append(holder_df_mean)
        
        holder_df_sum = df_analysis.groupby('Month')[i].sum()
        holder_df_sum = pd.DataFrame(holder_df_sum)
        list_of_df_sum.append(holder_df_sum)
        
        holder_df_sd = df_analysis.groupby('Month')[i].std()
        holder_df_sd = pd.DataFrame(holder_df_sd)
        list_of_df_sd.append(holder_df_sd)

    final_df_mean = pd.concat(list_of_df_mean, axis=1)
    final_df_sum = pd.concat(list_of_df_sum, axis=1)
    final_df_sd = pd.concat(list_of_df_sd, axis=1)
   
    
    for col in columns_to_be_scaled:
        df_analysis[f'{col}_quartile'] = pd.qcut(df_analysis[col], q=4, duplicates = 'drop').astype(str)

    for col in columns_to_be_scaled:
        numbers = df_analysis[f'{col}_quartile'].value_counts()


    mode_genre = df_analysis.groupby('Month')['encoded_genre'].agg(lambda x: x.mode()[0])
    mode_genre = pd.DataFrame(mode_genre)
    mode_genre = mode_genre.reset_index()

    inverted_genre = le.inverse_transform(mode_genre['encoded_genre'].astype(int))
    inverted_genre
    mode_genre['actual_genre'] = inverted_genre

    mode_artists = df_analysis.groupby('Month')['encoded_artists'].agg(lambda x: x.mode()[0])
    mode_artists = pd.DataFrame(mode_artists)
    mode_artists = mode_artists.reset_index()

    inverted_artists = le_two.inverse_transform(mode_artists['encoded_artists'].astype(int))
    inverted_artists
    mode_artists['actual_artists'] = inverted_artists

    result_holder = []
    for i in list(df_analysis.columns):
        if 'quartile' in i:
            for bin_value in sorted(df_analysis[i].unique()):
                bin_data = df_analysis[df_analysis[i] == bin_value]
                result = bin_data.sample(n=1, random_state=42).iloc[0]
    
                result['encoded_genre'] = le.inverse_transform([result['encoded_genre'].astype(int)])
                result['encoded_artists'] = le_two.inverse_transform([result['encoded_artists'].astype(int)])
    
                result_holder.append(result)
    
    df_with_data = pd.DataFrame([result_holder[0].values], columns=result_holder[0].index)
    
    for i, series in enumerate(result_holder[1:]):
        df_with_data.loc[i] = series.values
    
    cols = ['encoded_genre', 'encoded_artists'] + [col for col in df_with_data.columns if col not in ['encoded_genre', 'encoded_artists']]
    df_with_data = df_with_data[cols]
    df_with_data
    obj_cols = df_with_data.select_dtypes(include='object').columns
    df_with_data[obj_cols] = df_with_data[obj_cols].astype(str)


    return df_analysis,final_df_mean,final_df_sum,final_df_sd,df_with_data

In [25]:
scaled_df,final_df_mean,final_df_sum,final_df_sd,df_with_data = scaling_and_create_bins(result_df,le,le_two)

### Pushing Dataframes to MySQL Dataframe

In [26]:
# Connect to MySQL
conn = mysql.connector.connect(
    host="127.0.0.1",      # or "127.0.0.1"
    user="root",  # e.g., "root"
    password="quexopaloco2028$",
    database = "SpotifyUnWrapped"# optional if you want to connect to a specific database
)
cursor = conn.cursor()
engine = create_engine('mysql+mysqlconnector://root:quexopaloco2028$@127.0.0.1/SpotifyUnWrapped')

In [27]:
scaled_df.to_sql("song_metrics", engine, if_exists="replace", index=False)

489

In [28]:
final_df_mean.to_sql("mean_song_metrics", engine, if_exists="replace", index=False)

12

In [29]:
final_df_sum.to_sql("sum_song_metrics", engine, if_exists="replace", index=False)

12

In [30]:
final_df_sd.to_sql("sd_song_metrics", engine, if_exists="replace", index=False)

12

In [31]:
combined_df.to_sql("streaming_history_data", engine, if_exists="replace", index=False)

49982

In [32]:
albums_df.to_sql("album_history_data", engine, if_exists="replace", index=False)

170

In [33]:
podcastdf.to_sql("top_podcast_data", engine, if_exists="replace", index=False)

1

In [34]:
yearlymetricsdf.to_sql("yearly_metrics_data", engine, if_exists="replace", index=False)

1

In [35]:
evolutiondf.to_sql("evolution_df_data", engine, if_exists="replace", index=False)

18

In [36]:
stream_history_podcast.to_sql("streaming_podcast_data", engine, if_exists="replace", index=False)

511

In [37]:
popularity.to_sql("popularity_kaggle_data", engine, if_exists="replace", index=False)

114000

In [38]:
result_df.to_sql("metrics_for_my_songs", engine, if_exists="replace", index=False)

489

In [ ]:
df_with_data.head(10)